#!/bin/bash

#SBATCH -p hpc-bio-mendel
#SBATCH --chdir=/home/alumno21/lab-py-advan
#SBATCH -J submit_pi_par_solution-alumno21
#SBATCH --cpus-per-task=1

module load anaconda/2025.06

export OMP_NUM_THREAD=1

NOTEBOOK="pi-par-solution-alumno21.ipynb"

jupyter nbconvert --to script "$NOTEBOOK" --output pi-par-solution-alumno21

time srun ipython pi-par-solution-alumno21.py

module unload anaconda/2025.06
